# This workflow will verify the exercises in the repository
# using the track's test runner Docker image.

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Verify all exercises
        run: bin/verify-exercises-in-docker
